const state={view:'home',tasks:JSON.parse(localStorage.getItem('gst_tasks')||'[]'),expenses:JSON.parse(localStorage.getItem('gst_expenses')||'[]')};
const cats={Casa:'#ab858f',Cumples:'#a0acb9',Familia:'#9ebdb8',Médico:'#b3ad8c','Médicos familia':'#67a48b',Otros:'#7f9a7d',Social:'#9998b1',Vacaciones:'#cbafab',Viajes:'#9cabc8'};
const fmt=n=>new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR'}).format(n); const today=new Date();
function save(){localStorage.setItem('gst_tasks',JSON.stringify(state.tasks));localStorage.setItem('gst_expenses',JSON.stringify(state.expenses))}
function go(v){state.view=v;document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===v));render()}
function render(){const names={home:['Inicio',''],tasks:['Tareas','Pendientes y recordatorios'],expenses:['Gastos','Control mensual y cuentas'],food:['Comidas','Menú, inventario y recetas'],calendar:['Calendario','Eventos y cumpleaños'],settings:['Ajustes','Configura la aplicación']};document.querySelector('#pageTitle').textContent=names[state.view][0];document.querySelector('#pageSubtitle').textContent=names[state.view][1];const c=document.querySelector('#content');({home:home,tasks:tasks,expenses:expenses,food:food,calendar:calendar,settings:settings}[state.view])(c)}
function home(c){const d=today.toLocaleDateString('es-ES',{weekday:'long',day:'numeric',month:'long'});const pending=state.tasks.filter(x=>!x.done).length;const spent=state.expenses.filter(x=>x.type==='gasto'&&new Date(x.date).getMonth()===today.getMonth()).reduce((a,x)=>a+x.amount,0);c.innerHTML=`<div class="grid"><div class="card span-8"><div class="muted">Hoy</div><div class="metric">${d[0].toUpperCase()+d.slice(1)}</div><div class="calendar-mini"></div></div><div class="card span-4"><h3>Ahora</h3><div class="list"><div class="item"><b>${pending}</b> tareas pendientes</div><div class="item">Sin eventos urgentes</div></div><button class="primary" onclick="go('tasks')">Ver tareas</button></div><div class="card span-4"><h3>Tareas</h3><div class="metric">${pending}</div><span class="muted">pendientes</span></div><div class="card span-4"><h3>Gastos este mes</h3><div class="metric">${fmt(spent)}</div><span class="muted">de momento</span></div><div class="card span-4"><h3>Comidas</h3><div class="item">🍽 Comida pendiente de planificar</div><div class="item">🌙 Cena pendiente de planificar</div></div><div class="card span-12"><div class="row"><div><h3>Preparar esta semana</h3><span class="muted">Aquí conectaremos menú, preparaciones e inventario.</span></div><button class="secondary" onclick="go('food')">Ir a Comidas</button></div></div></div>`;renderMiniCalendar(c.querySelector('.calendar-mini'))}
function renderMiniCalendar(el){let y=today.getFullYear(),m=today.getMonth(),first=new Date(y,m,1).getDay();first=(first+6)%7;let days=new Date(y,m+1,0).getDate();let s='<div class="calendar"><div class="cal-head">L</div><div class="cal-head">M</div><div class="cal-head">X</div><div class="cal-head">J</div><div class="cal-head">V</div><div class="cal-head">S</div><div class="cal-head">D</div>';for(let i=0;i<first;i++)s+='<div></div>';for(let d=1;d<=days;d++){let ev= d%5===0?`<span class="dot" style="background:${cats.Social}"></span>`:'';s+=`<div class="day ${d===today.getDate()?'today':''}"><b>${d}</b><div>${ev}</div></div>`}el.innerHTML=s+'</div>'}
function tasks(c){const pending=state.tasks.filter(x=>!x.done).sort((a,b)=>(a.date||'9999').localeCompare(b.date||'9999'));c.innerHTML=`<div class="card"><div class="row"><h3>Pendientes</h3><span class="muted">${pending.length}</span></div><div class="list">${pending.length?pending.map(x=>`<div class="item task ${x.date&&new Date(x.date)<new Date(new Date().toDateString())?'overdue':''}"><input type="checkbox" onchange="completeTask('${x.id}')"><div><b>${esc(x.title)}</b><div class="muted">${x.date?new Date(x.date).toLocaleDateString('es-ES'):'Sin fecha'} · ${x.priority||'Normal'}</div></div></div>`).join(''):'<div class="muted">No tienes tareas pendientes 🎉</div>'}</div></div><div class="card" style="margin-top:18px"><h3>Categorías</h3><div class="actions"><span class="pill" style="background:#ebe9e2">Casas</span><span class="pill" style="background:#ebe9e2">Coches</span><span class="pill" style="background:#ebe9e2">Personal</span></div></div>`}
function expenses(c){const spent=state.expenses.filter(x=>x.type==='gasto').reduce((a,x)=>a+x.amount,0);c.innerHTML=`<div class="grid"><div class="card span-4"><h3>Este mes</h3><div class="metric">${fmt(spent)}</div><div class="progress"><i style="width:${Math.min(100,spent/1050*100)}%"></i></div><div class="muted" style="margin-top:8px">Presupuesto de ejemplo: ${fmt(1050)}</div></div><div class="card span-8"><h3>Últimos movimientos</h3><div class="list">${state.expenses.slice(-6).reverse().map(x=>`<div class="item row"><span>${esc(x.concept||x.category)}</span><b>${x.type==='gasto'?'-':'+'}${fmt(x.amount)}</b></div>`).join('')||'<div class="muted">Todavía no hay movimientos.</div>'}</div></div><div class="card span-12"><h3>Cuentas</h3><div class="actions"><span class="pill">Cuenta de gastos</span><span class="pill">Cuenta nómina</span><span class="pill">Cuenta ahorro</span><span class="pill">Revolut</span></div></div></div>`}
function food(c){c.innerHTML=`<div class="grid"><div class="card span-8"><h3>Menú semanal</h3><div class="list"><div class="item"><b>Lunes</b><br><span class="muted">Generar propuesta de comida y cena</span></div><div class="item"><b>Martes 🥡</b><br><span class="muted">Tupper</span></div><div class="item"><b>Viernes</b><br><span class="muted">🍕 Comida divertida</span></div></div><button class="primary" onclick="alert('El generador de menú se conectará en la siguiente fase.')">Generar menú</button></div><div class="card span-4"><h3>Inventario</h3><div class="item">❄️ Congelador</div><div class="item">🥫 Despensa</div><div class="item">🥬 Frescos</div><button class="secondary" onclick="alert('Inventario: siguiente fase')">Gestionar inventario</button></div><div class="card span-6"><h3>Recetas</h3><div class="actions"><span class="pill">Comidas</span><span class="pill">Cenas</span><span class="pill">Dulces</span><span class="pill">Pan</span><span class="pill">Preparaciones</span></div></div><div class="card span-6"><h3>Lista de la compra</h3><div class="muted">Se calculará automáticamente al aceptar un menú.</div></div></div>`}
function calendar(c){const evcats=Object.entries(cats).map(([n,col])=>`<span class="pill" style="background:${col}22;color:${col}">${n}</span>`).join('');c.innerHTML=`<div class="card"><div class="row"><h3>Septiembre 2026</h3><button class="primary" onclick="openModal('Nuevo evento',eventForm())">+ Evento</button></div><div class="calendar"><div class="cal-head">L</div><div class="cal-head">M</div><div class="cal-head">X</div><div class="cal-head">J</div><div class="cal-head">V</div><div class="cal-head">S</div><div class="cal-head">D</div>${Array.from({length:30},(_,i)=>`<div class="day ${i+1===today.getDate()?'today':''}"><b>${i+1}</b>${(i+1)%5===0?'<div><span class="dot" style="background:'+cats.Social+'"></span></div>':''}</div>`).join('')}</div><div class="actions">${evcats}</div></div>`}
function settings(c){c.innerHTML=`<div class="card"><h3>Preferencias</h3><div class="setting"><b>Apariencia</b><div class="muted">Base neutra, pastel moderno y modo oscuro preparado para una fase posterior.</div></div><div class="setting"><b>Calendario</b><div class="muted">Las categorías y colores definidos quedan preparados para edición.</div></div><div class="setting"><b>Datos</b><div class="muted">La V1 guarda los datos localmente. Después añadiremos copia/sincronización.</div></div><div class="setting"><b>PWA</b><div class="muted">La app está preparada para instalarse como aplicación en móvil.</div></div></div>`}
function eventForm(){return `<div class="form"><label>Título<input id="fTitle" required></label><label>Fecha<input id="fDate" type="date" value="${today.toISOString().slice(0,10)}"></label><label>Categoría<select id="fCat">${Object.keys(cats).map(x=>`<option>${x}</option>`).join('')}</select></label><label>Notas<textarea id="fNotes"></textarea></label><button class="primary" onclick="saveEvent()">Guardar</button></div>`}
function taskForm(){return `<div class="form"><label>Título<input id="fTitle" required></label><label>Fecha<input id="fDate" type="date"></label><label>Prioridad<select id="fPriority"><option>Normal</option><option>Importante</option><option>Urgente</option></select></label><label>Notas<textarea id="fNotes"></textarea></label><button class="primary" onclick="saveTask()">Guardar tarea</button></div>`}
function expenseForm(){return `<div class="form"><label>Importe<input id="fAmount" type="number" step="0.01" min="0"></label><label>Categoría<select id="fCat"><option>Comida</option><option>Alquiler</option><option>Seguro</option><option>Agua</option><option>Luz</option><option>Aerotermia</option><option>Móvil</option><option>Internet</option><option>Spotify</option><option>Podimo</option><option>ACNUR</option><option>Paga</option><option>Transporte</option><option>Otros gastos</option></select></label><label>Concepto<input id="fConcept"></label><label>Cuenta<select id="fAccount"><option>Cuenta de gastos</option><option>Cuenta nómina</option><option>Cuenta ahorro</option><option>Revolut</option></select></label><button class="primary" onclick="saveExpense()">Guardar gasto</button></div>`}
function openModal(t,b){document.querySelector('#modalTitle').textContent=t;document.querySelector('#modalBody').innerHTML=b;document.querySelector('#modal').classList.remove('hidden')}function closeModal(){document.querySelector('#modal').classList.add('hidden')}
function saveTask(){const title=document.querySelector('#fTitle').value.trim();if(!title)return;state.tasks.push({id:crypto.randomUUID(),title,date:document.querySelector('#fDate').value,priority:document.querySelector('#fPriority').value,done:false});save();closeModal();render()}
function saveExpense(){const amount=Number(document.querySelector('#fAmount').value);if(!amount)return;state.expenses.push({id:crypto.randomUUID(),amount,type:'gasto',category:document.querySelector('#fCat').value,concept:document.querySelector('#fConcept').value,account:document.querySelector('#fAccount').value,date:new Date().toISOString()});save();closeModal();render()}
function saveEvent(){alert('Evento guardado en el prototipo. En la siguiente fase se persistirá en la base de datos.');closeModal()}
function completeTask(id){const x=state.tasks.find(x=>x.id===id);if(x)x.done=true;save();render()}
function esc(s=''){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.view)));document.querySelector('#closeModal').addEventListener('click',closeModal);document.querySelector('#quickAdd').addEventListener('click',()=>{if(state.view==='tasks')openModal('Nueva tarea',taskForm());else if(state.view==='expenses')openModal('Nuevo gasto',expenseForm());else if(state.view==='calendar')openModal('Nuevo evento',eventForm());else if(state.view==='food')alert('Aquí elegiremos inventario, receta o preparación.');else openModal('Añadir',`<div class="actions"><button class="primary" onclick="closeModal();openModal('Nueva tarea',taskForm())">Nueva tarea</button><button class="secondary" onclick="closeModal();openModal('Nuevo gasto',expenseForm())">Nuevo gasto</button><button class="secondary" onclick="closeModal();openModal('Nuevo evento',eventForm())">Nuevo evento</button></div>`)});render();
